### ISSUE TITLE
Playground: Ctrl-Enter does nothing

### ISSUE THREAD

**Issue by yozlet** [topshell-language/topshell#1]
This is on Windows 10 in both Firefox 68 and Chrome 75.

I fill the code pane (left side) with an example, and the interpreter pane shows the various unevaluated declarations, including ones with `> Ctrl-Enter` underneath. Hitting Ctrl-Enter does nothing, but clicking the `>>` icon at the top triggers the execution correctly.

**Comment by tasuki** [comment]
The `>>` icon executes _all_ top level binds. `Ctrl-Enter` only executes the current line.

**Comment by yozlet** [comment]
@tasuki Thanks, now I see what the problem was: I didn't realise that I needed to have my cursor on the line being evaluated.

May I suggest: Hotkeys and UI elements should always do _something_, even if it's just showing an error.

**Comment by Ahnfelt** [comment]
@yozlet agreed.
